import turtle
import random
turtle.bgcolor('black')
turtle.pencolor('cyan')
for i in range(50):
    r =random.randint(20,210)
    d=random.randint(10,60)
    turtle.penup()
    turtle.goto(0,0)
    turtle.forward(r)
    turtle.left(90)
    turtle.pendown()
    turtle.circle(r,d)
    turtle.penup()
    turtle.goto(0,0)
turtle.pencolor('#9400D3')
for i in range(40):
    r =random.randint(5,210)
    d=random.randint(10,60)
    turtle.penup()
    turtle.goto(0,0)
    turtle.forward(r)
    turtle.left(90)
    turtle.pendown()
    turtle.circle(r,d)
    turtle.penup()
    turtle.goto(0,0)
turtle.pencolor('white')
for i in range(50):
    r =random.randint(30,210)
    d=random.randint(10,60)
    turtle.penup()
    turtle.goto(0,0)
    turtle.forward(r)
    turtle.left(90)
    turtle.pendown()
    turtle.circle(r,d)
    turtle.penup()
    turtle.goto(0,0)
turtle.pencolor('yellow')
for i in range(20):
    r =random.randint(30,210)
    d=random.randint(10,60)
    turtle.penup()
    turtle.goto(0,0)
    turtle.forward(r)
    turtle.left(90)
    turtle.pendown()
    turtle.circle(r,d)
    turtle.penup()
    turtle.goto(0,0)
